### ISSUE TITLE
Unable to Install

### ISSUE THREAD

**Issue by 007divyachawla** [dwisiswant0/proxylogscan#1]
After running this command getting this Error

┌──(root💀kali)-[~]
└─# go get dw1.io/proxylogscan                                                                                                                                             1 ⨯
# cd .; git clone -- https://github.com/kitabisa/mubeng/pkg/mubeng /root/go/src/ktbs.dev/mubeng/pkg/mubeng
Cloning into '/root/go/src/ktbs.dev/mubeng/pkg/mubeng'...
remote: Not Found
fatal: repository 'https://github.com/kitabisa/mubeng/pkg/mubeng/' not found
package ktbs.dev/mubeng/pkg/mubeng: exit status 128

Please let me know the solution for the same

**Comment by dwisiswant0** [comment]
Try prepend with `GO111MODULE=on`.

**Comment by 007divyachawla** [comment]
Thanks that work and thanks for quick reply
